xgboost:
  learning_rate: null
  max_depth: null
  colsample_bytree: null
  reg_alpha: null
  reg_lambda: null
  n_estimators: 10000
  # extra_trees: null
  scale_pos_weight: null
  # class_weight: null
  tree_method: "hist"

lightgbm:
  learning_rate: null
  max_depth: null
  num_leaves: null
  colsample_bytree: null
  reg_alpha: null
  reg_lambda: null
  n_estimators: 10000
  extra_trees: True
  class_weight: 'balanced'
  verbosity: -1